project:
  type: website

website:
  title: "PPortfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/02japes
      
format:
  html:
    theme: lux
    css: styles.css



