project:
  type: website
  output-dir: docs

website:
  title: "Jack Phillips"
  navbar:
    background: transparent
    right:
      - photography.qmd
      - about.qmd
      - icon: github
        href: https://github.com/02japes
      
format:
  html:
    theme: lux
    css: styles.css



